palbum/models.py
from datetime import datetime

from palbum import db
from palbum.constants import PhotoOrder


class DisplaySettings(db.Model):
    __tablename__ = "display_settings"
    id = db.Column(db.Integer, primary_key=True)
    photo_order = db.Column(
        db.String(24), nullable=False, default=PhotoOrder.SEQUENTIAL
    )
    display_time = db.Column(db.Integer, nullable=False, default=5)
    fade = db.Column(db.Boolean, nullable=False, default=False)

    def __repr__(self):
        return f"<DisplaySettings {self.photo_order} {self.display_time} {self.fade}>"


class Image(db.Model):
    __tablename__ = "images"
    id = db.Column(db.Integer, primary_key=True)
    added_at = db.Column(db.DateTime, nullable=False, default=datetime.utcnow)
    name = db.Column(db.Text, unique=True, nullable=False)
    is_visible = db.Column(db.Boolean, nullable=False, default=True)

    def __repr__(self):
        return f"<Image {self.id} {self.name}>"


class ImageMeta(db.Model):
    __tablename__ = "image_meta"
    id = db.Column(db.Integer, primary_key=True)
    last_image_id_shown = db.Column(db.Integer)

    def __repr__(self):
        return f"<ImageMeta {self.id} {self.last_image_id_shown}>"

palbum/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField
from wtforms import IntegerField
from wtforms import SelectField
from wtforms import SubmitField
from wtforms.validators import DataRequired
from wtforms.validators import NumberRange

from palbum.constants import PhotoOrder


class DisplaySettingsForm(FlaskForm):
    photo_order = SelectField(
        "Photo Order",
        choices=PhotoOrder.get_form_choices(),
        validators=[DataRequired()],
    )
    display_time = IntegerField(
        "Photo Display Time (seconds)",
        validators=[
            DataRequired(),
            NumberRange(min=1, max=61, message="Display time must be 0 and 60"),
        ],
    )
    fade = BooleanField("Fade Out Transition")
    submit = SubmitField("Submit")

palbum/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_moment import Moment
from flask_sqlalchemy import SQLAlchemy

from config import config

db = SQLAlchemy()
migrate = Migrate()
moment = Moment()


def create_app():
    app = Flask(__name__)

    app.config.from_object(config["config"])

    db.init_app(app)
    migrate.init_app(app, db)
    moment.init_app(app)

    from palbum.routes import main

    app.register_blueprint(main)

    from palbum import commands
    from palbum import models  # noqa: F401

    app.cli.add_command(commands.download_images)

    if app.debug:
        from palbum import model_storage  # noqa: F401

        @app.shell_context_processor
        def make_shell_context():
            return {
                "db": db,
                "DisplaySettings": models.DisplaySettings,
                "DisplaySettingsModelStorage": model_storage.DisplaySettingseModelStorage,
                "Image": models.Image,
                "ImageModelStorage": model_storage.ImageModelStorage,
                "ImageMetaModelStorage": model_storage.ImageMetaModelStorage,
            }

    return app

palbum/routes.py
from flask import Blueprint
from flask import redirect
from flask import render_template
from flask import request
from flask import url_for

from palbum.forms import DisplaySettingsForm
from palbum.model_storage import DisplaySettingseModelStorage
from palbum.model_storage import ImageModelStorage
from palbum.utils import download_images_from_dbx_async

main = Blueprint("main", __name__)


@main.route("/", methods=["GET", "POST"])
def home():
    form = DisplaySettingsForm()
    if form.validate_on_submit():
        DisplaySettingseModelStorage.update(
            photo_order=form.photo_order.data,
            display_time=form.display_time.data,
            fade=form.fade.data,
        )
        return redirect(url_for("main.home"))

    settings = DisplaySettingseModelStorage.read()
    if settings:
        form.photo_order.data = settings.photo_order
        form.display_time.data = settings.display_time
        form.fade.data = settings.fade
    return render_template("index.html", form=form, settings=settings)


@main.route("/image")
def image():
    image = ImageModelStorage.get_image_to_display()
    return render_template("components/image.html", image=image)


@main.route("/images")
def images():
    page = request.args.get("page", 1, type=int)
    images = ImageModelStorage.get_all_images_by_added_at(page=page)
    image_stats = ImageModelStorage.get_all_image_stats()
    return render_template("images.html", images=images, image_stats=image_stats)


@main.route("/image/toggle/<int:image_id>", methods=["POST"])
def image_toggle(image_id):
    image = ImageModelStorage.toggle_visibility(image_id)
    return render_template("components/image-manager-image.html", image=image)


@main.route("/download-images")
def download_images():
    download_images_from_dbx_async()
    return render_template("downloading.html")

palbum/templates/_base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://unpkg.com/htmx.org@1.9.10"
        integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous">
    </script>
    {{ moment.include_moment() }}
    <style>
        .fade-me-out.htmx-swapping {
            opacity: 0;
            transition: opacity 1s ease-out;
        }
    </style>

    <title>palbum</title>
</head>

<body>
    <div class="m-1">

        {% block content %}{% endblock %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous">
    </script>
</body>

</html>

palbum/templates/components/image-manager-image.html
{% import "macros/display_image.html" as display_image %}
{{ display_image.display_image(image) }}

palbum/templates/components/image.html
<div>
    {% if image %}
    <img style="max-width: 100%; max-height: 90vh;"
        src="{{ url_for('static', filename='images/{}'.format(image.name)) }}">
    {% else %}
    <div class="d-flex flex-column align-items-center">
        <p>No image returned!</p>
        <p>Please check that images have been downloaded and that an appropriate photo order has been selected!</p>
    </div>
    {% endif %}
</div>

palbum/templates/downloading.html
{% extends '_base.html' %}

{% block content %}
<div class="p-5 text-center">
    <p>Checking for new images!</p>
    <p>This may take a little bit...</p>
    <p>Check back <a href="{{ url_for('main.images') }}">here</a> in just a few!</p>
</div>


{% endblock %}

palbum/templates/images.html
{% import "macros/display_image.html" as display_image %}
{% extends '_base.html' %}

{% block content %}
<div class="d-flex justify-content-between">
    <button type="button" class="btn btn-link link-secondary link-underline link-underline-opacity-0">
        <a class="text-decoration-none text-reset" href="{{ url_for('main.home') }}">Home</a>
    </button>
    <button type="button" class="btn btn-link link-secondary link-underline link-underline-opacity-0">
        <a class="text-decoration-none text-reset" href="{{ url_for('main.images') }}">Reload</a>
    </button>
    <button type="button" class="btn btn-link link-secondary link-underline link-underline-opacity-0">
        <a class="text-decoration-none text-reset" href="{{ url_for('main.download_images') }}">Check for<br> New
            Images</a>
    </button>
</div>

<h1 class="py-3 text-center">Image Manager</h1>

{% if image_stats %}
<div class="d-flex justify-content-between pb-3 px-5">
    <div class="d-flex flex-column align-items-center">
        <p class="lh-1 m-0">{{ image_stats['total'] }}</p>
        <p class="lh-1 m-0">Images</p>
    </div>
    <div>
        <div class="d-flex flex-column align-items-center">
            <p class="lh-1 m-0">{{ image_stats['visible'] }}</p>
            <p class="lh-1 m-0">Visible Images</p>
        </div>
    </div>
    <div>
        <div class="d-flex flex-column align-items-center">
            <p class="lh-1 m-0">{{ image_stats['hidden'] }}</p>
            <p class="lh-1 m-0">Hidden Images</p>
        </div>
    </div>
    <div>
        <div class="d-flex flex-column align-items-center">
            <p class="lh-1 m-0">{{ moment(image_stats['last_image_added_at']).fromNow() }}</p>
            <p class="lh-1 m-0">Last Image Added At</p>
        </div>
    </div>
</div>
{% endif %}

{% if images %}
<div class="container d-flex flex-wrap justify-content-around">
    {% for image in images %}
    {{ display_image.display_image(image) }}
    {% endfor %}
</div>
<div class="container py-2 d-flex justify-content-center">
    {% for page_num in images.iter_pages() %}
    {% if page_num %}
    <div class="p-1">
        {% if page_num == images.page %}
        <a class="btn btn-secondary" href="{{ url_for('main.images', page=page_num) }}">{{ page_num }}</a>
        {% else %}
        <a class="btn btn-outline-primary" href="{{ url_for('main.images', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    </div>
    {% else%}
    ...
    {% endif %}
    {% endfor %}
</div>
{% endif %}



{% endblock %}

palbum/templates/index.html
{% extends '_base.html' %}

{% block content %}

<!-- Button trigger modal -->
<button type="button" class="btn btn-link link-secondary link-underline link-underline-opacity-0" data-bs-toggle="modal"
    data-bs-target="#settingsModal">
    Settings
</button>

<!-- Modal -->
<div class="modal fade" id="settingsModal" tabindex="-1" aria-labelledby="settingsModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="settingsModalLabel">Settings</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="pb-1">
                    <button type="button" class="btn btn-success">
                        <a href="{{ url_for('main.images') }}" class="text-decoration-none text-reset">Images</a>
                    </button>
                    <hr>
                </div>
                <form method="POST" action="{{ url_for('main.home') }}">
                    {{ form.hidden_tag() }}
                    <fieldset class="form-group">
                        <!-- Photo Order -->
                        <div class="form-group mb-1">
                            {% if form.photo_order.errors %}
                            {{ form.photo_order(class="form-control form-control-md is-invalid") }}
                            <div class="invalid-feedback font-weight-bold">
                                {% for error in form.photo_order.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.photo_order.label(class="form-control-label") }}
                            {{ form.photo_order(class="form-control form-control-md", placeholder="Photo Order") }}
                            {% endif %}
                        </div>
                        <!-- Display Time -->
                        <div class="form-group mb-1">
                            {% if form.display_time.errors %}
                            {{ form.display_time(class="form-control form-control-md is-invalid") }}
                            <div class="invalid-feedback font-weight-bold">
                                {% for error in form.display_time.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                            {% else %}
                            {{ form.display_time.label(class="form-control-label") }}
                            {{ form.display_time(class="form-control form-control-md", placeholder="Photo Display Time (seconds)") }}
                            {% endif %}
                        </div>
                        <!-- Fade -->
                        <div class="form-check">
                            {{ form.fade(class="form-check-input") }}
                            {{ form.fade.label(class="form-check-label", placeholder="Fade Images Out") }}
                        </div>
                    </fieldset>

                    <div class="modal-footer mt-3">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                        {{ form.submit(class="btn btn-primary") }}
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

<div class="d-flex align-items-center justify-content-center">
    {% if settings and settings.fade %}
    <div class="fade-me-out" hx-get="/image" hx-trigger="every {{ settings.display_time }}s"
        hx-swap="innerHTML swap:1s">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
    {% else %}
    <div hx-get="/image" hx-trigger="every {{ settings.display_time if settings and settings.display_time else 5 }}s">
        <div class="spinner-border" role="status">
            <span class="visually-hidden">Loading...</span>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}

palbum/templates/macros/display_image.html
{% macro display_image(image) -%}
<div id="image-{{ image.id }}" class="p-2">
    <div class="d-flex flex-column align-items-center">
        <figure class="figure {{ 'border border-danger rounded' if not image.is_visible else '' }}">
            <img class="img-thumbnail" style="max-width: 300px; height:auto" src="static/images/{{ image.name }}">
        </figure>
        {% if not image.is_visible %}
        <button type="button" class="btn btn-success">
            <a hx-target="#image-{{ image.id }}" hx-swap="outerHTML"
                hx-post="{{ url_for('main.image_toggle', image_id=image.id) }}"
                class="text-decoration-none text-reset">Show</a>
        </button>
        {% else %}
        <button type="button" class="btn btn-danger">
            <a hx-target="#image-{{ image.id }}" hx-swap="outerHTML"
                hx-post="{{ url_for('main.image_toggle', image_id=image.id) }}"
                class="text-decoration-none text-reset">Hide</a>
        </button>
        {% endif %}
    </div>
</div>
{%- endmacro %}

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://unpkg.com/htmx.org@1.9.10"
        integrity="sha384-D1Kt99CQMDuVetoL1lrYwg5t+9QdHe7NLX/SoJYkXDFfX37iInKRy5xLSi8nO7UC" crossorigin="anonymous">
    </script>
    <style>
        .fade-me-out.htmx-swapping {
            opacity: 0;
            transition: opacity 1s ease-out;
        }
    </style>

    <title>palbum</title>
</head>

<body>
    <div class="m-1">
        <!-- Button trigger modal -->
        <button type="button" class="btn btn-link link-secondary link-underline link-underline-opacity-0"
            data-bs-toggle="modal" data-bs-target="#settingsModal">
            Settings
        </button>

        <!-- Modal -->
        <div class="modal fade" id="settingsModal" tabindex="-1" aria-labelledby="settingsModalLabel"
            aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5" id="settingsModalLabel">Display Settings</h1>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        <form method="POST" action="{{ url_for('home') }}">
                            {{ form.hidden_tag() }}
                            <fieldset class="form-group">
                                <!-- Photo Order -->
                                <div class="form-group mb-1">
                                    {% if form.photo_order.errors %}
                                    {{ form.photo_order(class="form-control form-control-md is-invalid") }}
                                    <div class="invalid-feedback font-weight-bold">
                                        {% for error in form.photo_order.errors %}
                                        <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.photo_order.label(class="form-control-label") }}
                                    {{ form.photo_order(class="form-control form-control-md", placeholder="Photo Order") }}
                                    {% endif %}
                                </div>
                                <!-- Display Time -->
                                <div class="form-group mb-1">
                                    {% if form.display_time.errors %}
                                    {{ form.display_time(class="form-control form-control-md is-invalid") }}
                                    <div class="invalid-feedback font-weight-bold">
                                        {% for error in form.display_time.errors %}
                                        <span>{{ error }}</span>
                                        {% endfor %}
                                    </div>
                                    {% else %}
                                    {{ form.display_time.label(class="form-control-label") }}
                                    {{ form.display_time(class="form-control form-control-md", placeholder="Photo Display Time (seconds)") }}
                                    {% endif %}
                                </div>
                                <!-- Fade -->
                                <div class="form-check">
                                    {{ form.fade(class="form-check-input") }}
                                    {{ form.fade.label(class="form-check-label", placeholder="Fade Images Out") }}
                                </div>
                            </fieldset>

                            <div class="modal-footer mt-3">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                {{ form.submit(class="btn btn-primary") }}
                            </div>
                        </form>
                    </div>

                </div>
            </div>
        </div>

        <div class="d-flex align-items-center justify-content-center">
            {% if settings.fade %}
            <div class="fade-me-out" hx-get="/image" hx-trigger="every {{ settings.display_time }}s"
                hx-swap="innerHTML swap:1s">
            </div>
            {% else %}
            <div hx-get="/image" hx-trigger="every {{ settings.display_time }}s"></div>
            {% endif %}
        </div>
    </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js"
        integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous">
    </script>
</body>

</html>